In [1]:
import torch

In [2]:
import torch

# Check PyTorch version
print("PyTorch version:", torch.__version__)

# Check for GPU availability
print("Is CUDA available?", torch.cuda.is_available())


PyTorch version: 2.5.1+cpu
Is CUDA available? False


In [3]:
import torch

# Check if CUDA is available
print("Is CUDA available?", torch.cuda.is_available())

# If you want to check if PyTorch is using the GPU
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("Using CPU for computations")


Is CUDA available? False
Using CPU for computations


In [15]:
scaler = torch.Tensor(1)

In [17]:
scaler

tensor([2.])

In [20]:
vector = torch.Tensor(2,3)
vector,vector.ndim

(tensor([[-5.5543e-17,  1.4602e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]),
 2)

In [21]:
scaler.item()

2.0

In [22]:
vector.shape

torch.Size([2, 3])

In [19]:
scaler.shape

torch.Size([1])

In [40]:
randro = torch.rand(size=(3,3,3)).int()

In [41]:
randro

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [42]:
randro.ndim , randro.shape , randro.dtype

(3, torch.Size([3, 3, 3]), torch.int32)

In [50]:
with_arabge = torch.arange(0,10,1)

In [51]:
with_arabge

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
r_tansor=torch.tensor(data=[1,2,3] ,
                      dtype=torch.float32, requires_grad=False)

In [58]:
r_tensor = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=False)


In [65]:
r_tensor.dtype , r_tensor.device

(torch.float32, device(type='cpu'))

In [66]:
from torch import nn

In [81]:
# Example input tensor with shape (batch_size=2, input_features=3)
input_tensor = torch.randn(2, 3)

# Define the linear layer
linear_tensors = nn.Linear(in_features=3, out_features=4)

# Apply the linear transformation
output_tensor = linear_tensors(input_tensor)

In [82]:
output_tensor

tensor([[ 0.1470, -0.4191, -0.2914,  0.1459],
        [ 0.7754, -1.1850, -0.0357, -1.2502]], grad_fn=<AddmmBackward0>)

In [93]:
y=torch.transpose(output_tensor,dim0=1,dim1=0)

In [94]:
y

tensor([[ 0.1470,  0.7754],
        [-0.4191, -1.1850],
        [-0.2914, -0.0357],
        [ 0.1459, -1.2502]], grad_fn=<TransposeBackward0>)

In [95]:
y.mean()

tensor(-0.2642, grad_fn=<MeanBackward0>)

In [102]:
y.reshape(-1,1
          ).shape

torch.Size([8, 1])

In [101]:
y.shape

torch.Size([4, 2])

In [105]:
stack = torch.stack([y,y]) # to concat 

In [106]:
stack

tensor([[[ 0.1470,  0.7754],
         [-0.4191, -1.1850],
         [-0.2914, -0.0357],
         [ 0.1459, -1.2502]],

        [[ 0.1470,  0.7754],
         [-0.4191, -1.1850],
         [-0.2914, -0.0357],
         [ 0.1459, -1.2502]]], grad_fn=<StackBackward0>)

In [114]:
stack_r=stack.reshape([-1,1])

In [116]:
stack_r.squeeze(),stack_r.squeeze().shape

(tensor([ 0.1470,  0.7754, -0.4191, -1.1850, -0.2914, -0.0357,  0.1459, -1.2502,
          0.1470,  0.7754, -0.4191, -1.1850, -0.2914, -0.0357,  0.1459, -1.2502],
        grad_fn=<SqueezeBackward0>),
 torch.Size([16]))

In [121]:
stack_r.unsqueeze(dim=1),stack_r.unsqueeze(dim=1).shape

(tensor([[[ 0.1470]],
 
         [[ 0.7754]],
 
         [[-0.4191]],
 
         [[-1.1850]],
 
         [[-0.2914]],
 
         [[-0.0357]],
 
         [[ 0.1459]],
 
         [[-1.2502]],
 
         [[ 0.1470]],
 
         [[ 0.7754]],
 
         [[-0.4191]],
 
         [[-1.1850]],
 
         [[-0.2914]],
 
         [[-0.0357]],
 
         [[ 0.1459]],
 
         [[-1.2502]]], grad_fn=<UnsqueezeBackward0>),
 torch.Size([16, 1, 1]))

In [124]:
torch.manual_seed(42)
torch.rand(2,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [126]:
torch.cuda.is_available()

False

In [129]:
type_tensor=tensor_l.to("cpu")

In [130]:
type(type_tensor)

torch.Tensor

In [2]:
def cusal_mask(size):
        mask =torch.triu(torch.ones(1 , size , size ) , diagonal=1).type(torch.int)
        return mask ==0

In [13]:
dec_inputc=torch.Tensor(size=(1,3,3))

In [14]:
dec_inputc

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
cusal_mask(dec_inputc.size(0))

tensor([[[True]]])

In [55]:
mask = torch.triu(torch.ones(1,3 , 3 ) , diagonal=1 ).type(torch.int)

In [56]:
mask ==0

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [54]:
mask ==0

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [28]:
x= mask ==0

In [29]:
x

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [48]:
x= torch.arange(0,9,3)

In [49]:
x , x.size()


(tensor([0, 3, 6]), torch.Size([3]))

In [50]:
((x==0).unsqueeze(0) & cusal_mask(x.size(0)) )

tensor([[[ True, False, False],
         [ True, False, False],
         [ True, False, False]]])

In [ ]:
def cusal_mask(size):
        mask =torch.triu(torch.ones( size , size ) , diagonal=1).type(torch.int)
        return mask ==0